## Perform Signal-Space Separation (SSS) and Maxwell filtering

This step performs Maxwell filtering with tSSS (10 s window) on each run to suppress environmental noise, sensor cross-talk, and head-movement–related artifacts using site-specific calibration (`sss_cal.dat`) and cross-talk (`ct_sparse.fif`) files. Data from every run are transformed to a common head position (the first run’s `dev_head_t`) to standardize head geometry across runs. Each filtered run is saved (`_sss_raw.fif`). The filtered runs are then concatenated into a single continuous Raw object (`_ALL_sss_raw.fif`). *This is the file that should be fed into ICA in the next step.*

#### What's tSSS?
Signal Space Separation (SSS) is a Maxwell-equation–based method that expands MEG sensor data into spherical-harmonic components originating inside vs. outside the helmet. By modeling the magnetic field, SSS retains “internal” brain sources and suppresses “external” interference; temporal SSS (tSSS) further rejects artifacts by removing components whose time courses match external sources across a sliding window. Here, SSS/tSSS are applied with site calibration and cross-talk files, data are transformed to the first run’s head position, each run is saved, then all runs are concatenated for analysis.

*Requires unfiltered data and calibration files (sss_cal.dat, ct_sparse.fif)*

In [1]:
# load packages
import os
import time
import numpy as np
import mne
from mne.io import read_raw_fif
from mne.preprocessing import maxwell_filter

In [2]:
# session info
subject = 'nbl_010'
session = '01'
files = ['bigfrank_1', 'bigfrank_2', 'bigfrank_3', 'emptyroom'] # 'pharyperc'

In [3]:
# file paths
processed_meg_dir = '/mnt/sphere/nbl/processed_meg/'
sub_ses = os.path.join(subject, 'ses-'+session)
bads_list_fname = os.path.join(processed_meg_dir, sub_ses, '%s_bads.txt'%(subject))
with open(bads_list_fname, 'r') as f: bads = [line.strip() for line in f.readlines()]
print('Bad channels:',bads)
raw_fnames = [os.path.join(processed_meg_dir, sub_ses, subject+'_'+f+'_raw.fif') for f in files]
raw_fnames

Bad channels: ['MEG1132', 'MEG1543', 'MEG1843']


['/mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_1_raw.fif',
 '/mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_2_raw.fif',
 '/mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_3_raw.fif',
 '/mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_emptyroom_raw.fif']

In [4]:
# Step 1: Load raw files and static head positions
raw_list = []

for idx, file in enumerate(files):
    fname = os.path.join(processed_meg_dir, sub_ses, f"{subject}_{file}_raw.fif")
    print(f"\n{'='*60}")
    print(f"Processing file {idx+1}/{len(files)}: {os.path.basename(fname)}")
    print('='*60)
    
    # load raw data
    print(f"Loading raw file...")
    t = time.time()
    raw = read_raw_fif(fname, preload=True, verbose=False)
    raw.info["bads"] = bads  # important!
    print(f"Loaded in {time.time() - t:.1f} seconds.\n")
    
    raw_list.append(raw)
    
    if file != 'emptyroom':
        print(f"File {idx+1} head position:")
        print(raw.info['dev_head_t']['trans'])


Processing file 1/4: nbl_008_bigfrank_1_raw.fif
Loading raw file...
Loaded in 34.2 seconds.

File 1 head position:
[[ 0.99943793 -0.0323722  -0.00866533 -0.00312324]
 [ 0.03341955  0.94360483  0.32938153 -0.00347099]
 [-0.00248616 -0.32948613  0.94415677  0.07106136]
 [ 0.          0.          0.          1.        ]]

Processing file 2/4: nbl_008_bigfrank_2_raw.fif
Loading raw file...
Loaded in 28.9 seconds.

File 2 head position:
[[ 0.99986041  0.00833376 -0.01446839 -0.00381067]
 [-0.00589885  0.98696291  0.16083914 -0.0080237 ]
 [ 0.01562016 -0.16073138  0.98687446  0.06991964]
 [ 0.          0.          0.          1.        ]]

Processing file 3/4: nbl_008_bigfrank_3_raw.fif
Loading raw file...
Loaded in 19.7 seconds.

File 3 head position:
[[ 0.99476647  0.01374814 -0.10124592 -0.00688846]
 [-0.00447471  0.99581742  0.09125648 -0.00646582]
 [ 0.10207704 -0.09032584  0.99066722  0.06641855]
 [ 0.          0.          0.          1.        ]]

Processing file 4/4: nbl_008_emptyro

In [5]:
# Step 2: Maxwell filter
cal_fname = '/mnt/sphere/nbl/sss/sss_cal.dat'   # calibration file
ct_fname = '/mnt/sphere/nbl/sss/ct_sparse.fif'  # cross-talk file

# process each file with Maxwell filtering & transform to initial head position
destination = raw_list[0].info['dev_head_t']
raw_sss_list = []
for idx, (file, raw) in enumerate(zip(files, raw_list)):
    print(f"\n{'='*60}")
    print(f"Maxwell filtering file {idx+1}/3: {subject}_{file}_raw.fif")
    print(f"{'='*60}")
    print(f"Applying Maxwell filter with tSSS...")
    t = time.time()
    if file == 'emptyroom':
        raw_sss = maxwell_filter(raw, calibration=cal_fname, cross_talk=ct_fname, coord_frame='meg',
                                 destination=None, st_duration=10, origin='auto', verbose=True)
    else:
        raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, coord_frame='head',
                                 destination=destination, st_duration=10, origin=(0., 0., 0.04), verbose=True)
    elapsed = time.time() - t
    print(f"Maxwell filtering completed in {elapsed:.1f} seconds")
    if len(raw.ch_names) != len(raw_sss.ch_names):
        raise RuntimeError(f"Lost channels: Raw has {len(raw.ch_names)} channels; Raw_sss has {len(raw_sss.ch_names)} channels")
    
    if file == 'emptyroom':
        # bandpass filter now because the data won't be ICA-processed
        raw_sss = raw_sss.filter(1, 200, picks='meg', n_jobs=-1)
        raw_sss = raw_sss.notch_filter(60, picks='meg', n_jobs=-1)
    else:
        raw_sss_list.append(raw_sss)
    
    # save
    sss_fname = os.path.join(processed_meg_dir, sub_ses, f"{subject}_{file}_sss_raw.fif")
    raw_sss.save(sss_fname, overwrite=True)
    print(f"Saved to: {sss_fname}")

# concatenate all Maxwell filtered files
raw_concat = mne.concatenate_raws(raw_sss_list, preload=True)
print(f"Concatenated data:")
print(f"  Duration: {raw_concat.times[-1]:.1f} seconds ({raw_concat.times[-1]/60:.1f} minutes)")
print(f"  Samples: {len(raw_concat.times)}")
print(f"  Channels: {len(raw_concat.copy().pick('meg').ch_names)} MEG, ")

# save concatenated file
concat_fname = os.path.join(processed_meg_dir, sub_ses, f"{subject}_ALL_sss_raw.fif")
raw_concat.save(concat_fname, overwrite=True)
print(f"\nSaved concatenated file to: {concat_fname}")


Maxwell filtering file 1/3: nbl_008_bigfrank_1_raw.fif
Applying Maxwell filter with tSSS...
Maxwell filtering raw data
102 of 102 magnetometer types replaced with T3.
    Bad MEG channels being reconstructed: ['MEG1132', 'MEG1543', 'MEG1843']
    Processing 204 gradiometers and 102 magnetometers
    Using fine calibration sss_cal.dat
        Adjusting non-orthogonal EX and EY
        Adjusted coil orientations by (μ ± σ): 0.5° ± 0.4° (max: 2.4°)
    Using origin 0.0, 0.0, 40.0 mm in the head frame
    Processing data using tSSS with st_duration=10.0
    Using loaded raw data
        Using 84/95 harmonic components for    0.000  (69/80 in, 15/15 out)
    Processing  204 data chunks of (at least) 10.0 s with 0.0 s overlap and boxcar windowing
    The final 2.0 s will be lumped into the final window
        Using 84/95 harmonic components for    0.000  (69/80 in, 15/15 out)
        Projecting  0 intersecting tSSS components for    0.000 -    9.999 s


/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for   10.000 -   19.999 s
        Projecting  1 intersecting tSSS component  for   20.000 -   29.999 s
        Projecting  0 intersecting tSSS components for   30.000 -   39.999 s
        Projecting  1 intersecting tSSS component  for   40.000 -   49.999 s
        Projecting  0 intersecting tSSS components for   50.000 -   59.999 s
        Projecting  0 intersecting tSSS components for   60.000 -   69.999 s
        Projecting  1 intersecting tSSS component  for   70.000 -   79.999 s
        Projecting  0 intersecting tSSS components for   80.000 -   89.999 s
        Projecting  0 intersecting tSSS components for   90.000 -   99.999 s
        Projecting  1 intersecting tSSS component  for  100.000 -  109.999 s
        Projecting  1 intersecting tSSS component  for  110.000 -  119.999 s
        Projecting  0 intersecting tSSS components for  120.000 -  129.999 s
        Projecting  0 intersecting tSSS components for  130.000 -  139.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for  210.000 -  219.999 s
        Projecting  1 intersecting tSSS component  for  220.000 -  229.999 s
        Projecting  0 intersecting tSSS components for  230.000 -  239.999 s
        Projecting  0 intersecting tSSS components for  240.000 -  249.999 s
        Projecting  0 intersecting tSSS components for  250.000 -  259.999 s
        Projecting  0 intersecting tSSS components for  260.000 -  269.999 s
        Projecting  0 intersecting tSSS components for  270.000 -  279.999 s
        Projecting  0 intersecting tSSS components for  280.000 -  289.999 s
        Projecting  0 intersecting tSSS components for  290.000 -  299.999 s
        Projecting  0 intersecting tSSS components for  300.000 -  309.999 s
        Projecting  0 intersecting tSSS components for  310.000 -  319.999 s
        Projecting  0 intersecting tSSS components for  320.000 -  329.999 s
        Projecting  0 intersecting tSSS components for  330.000 -  339.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for  370.000 -  379.999 s
        Projecting  0 intersecting tSSS components for  380.000 -  389.999 s
        Projecting  0 intersecting tSSS components for  390.000 -  399.999 s
        Projecting  0 intersecting tSSS components for  400.000 -  409.999 s
        Projecting  0 intersecting tSSS components for  410.000 -  419.999 s
        Projecting  0 intersecting tSSS components for  420.000 -  429.999 s
        Projecting  0 intersecting tSSS components for  430.000 -  439.999 s
        Projecting  0 intersecting tSSS components for  440.000 -  449.999 s
        Projecting  1 intersecting tSSS component  for  450.000 -  459.999 s
        Projecting  0 intersecting tSSS components for  460.000 -  469.999 s


/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for  470.000 -  479.999 s
        Projecting  0 intersecting tSSS components for  480.000 -  489.999 s
        Projecting  0 intersecting tSSS components for  490.000 -  499.999 s
        Projecting  0 intersecting tSSS components for  500.000 -  509.999 s
        Projecting  0 intersecting tSSS components for  510.000 -  519.999 s
        Projecting  0 intersecting tSSS components for  520.000 -  529.999 s
        Projecting  0 intersecting tSSS components for  530.000 -  539.999 s
        Projecting  0 intersecting tSSS components for  540.000 -  549.999 s
        Projecting  0 intersecting tSSS components for  550.000 -  559.999 s
        Projecting  0 intersecting tSSS components for  560.000 -  569.999 s
        Projecting  1 intersecting tSSS component  for  570.000 -  579.999 s
        Projecting  0 intersecting tSSS components for  580.000 -  589.999 s
        Projecting  0 intersecting tSSS components for  590.000 -  599.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for  710.000 -  719.999 s
        Projecting  0 intersecting tSSS components for  720.000 -  729.999 s
        Projecting  0 intersecting tSSS components for  730.000 -  739.999 s
        Projecting  0 intersecting tSSS components for  740.000 -  749.999 s
        Projecting  0 intersecting tSSS components for  750.000 -  759.999 s
        Projecting  0 intersecting tSSS components for  760.000 -  769.999 s
        Projecting  0 intersecting tSSS components for  770.000 -  779.999 s
        Projecting  0 intersecting tSSS components for  780.000 -  789.999 s
        Projecting  0 intersecting tSSS components for  790.000 -  799.999 s
        Projecting  2 intersecting tSSS components for  800.000 -  809.999 s
        Projecting  1 intersecting tSSS component  for  810.000 -  819.999 s
        Projecting  0 intersecting tSSS components for  820.000 -  829.999 s
        Projecting  0 intersecting tSSS components for  830.000 -  839.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for 1140.000 - 1149.999 s
        Projecting  0 intersecting tSSS components for 1150.000 - 1159.999 s
        Projecting  1 intersecting tSSS component  for 1160.000 - 1169.999 s
        Projecting  0 intersecting tSSS components for 1170.000 - 1179.999 s
        Projecting  0 intersecting tSSS components for 1180.000 - 1189.999 s
        Projecting  0 intersecting tSSS components for 1190.000 - 1199.999 s
        Projecting  0 intersecting tSSS components for 1200.000 - 1209.999 s
        Projecting  0 intersecting tSSS components for 1210.000 - 1219.999 s
        Projecting  0 intersecting tSSS components for 1220.000 - 1229.999 s
        Projecting  0 intersecting tSSS components for 1230.000 - 1239.999 s
        Projecting  0 intersecting tSSS components for 1240.000 - 1249.999 s


/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for 1250.000 - 1259.999 s
        Projecting  0 intersecting tSSS components for 1260.000 - 1269.999 s
        Projecting  0 intersecting tSSS components for 1270.000 - 1279.999 s
        Projecting  1 intersecting tSSS component  for 1280.000 - 1289.999 s
        Projecting  0 intersecting tSSS components for 1290.000 - 1299.999 s
        Projecting  0 intersecting tSSS components for 1300.000 - 1309.999 s
        Projecting  0 intersecting tSSS components for 1310.000 - 1319.999 s
        Projecting  0 intersecting tSSS components for 1320.000 - 1329.999 s
        Projecting  0 intersecting tSSS components for 1330.000 - 1339.999 s
        Projecting  0 intersecting tSSS components for 1340.000 - 1349.999 s
        Projecting  0 intersecting tSSS components for 1350.000 - 1359.999 s
        Projecting  0 intersecting tSSS components for 1360.000 - 1369.999 s
        Projecting  0 intersecting tSSS components for 1370.000 - 1379.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  1 intersecting tSSS component  for 1400.000 - 1409.999 s
        Projecting  0 intersecting tSSS components for 1410.000 - 1419.999 s
        Projecting  0 intersecting tSSS components for 1420.000 - 1429.999 s
        Projecting  0 intersecting tSSS components for 1430.000 - 1439.999 s
        Projecting  0 intersecting tSSS components for 1440.000 - 1449.999 s
        Projecting  0 intersecting tSSS components for 1450.000 - 1459.999 s
        Projecting  0 intersecting tSSS components for 1460.000 - 1469.999 s
        Projecting  0 intersecting tSSS components for 1470.000 - 1479.999 s
        Projecting  0 intersecting tSSS components for 1480.000 - 1489.999 s
        Projecting  0 intersecting tSSS components for 1490.000 - 1499.999 s
        Projecting  0 intersecting tSSS components for 1500.000 - 1509.999 s
        Projecting  0 intersecting tSSS components for 1510.000 - 1519.999 s
        Projecting  1 intersecting tSSS component  for 1520.000 - 1529.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for 1570.000 - 1579.999 s
        Projecting  0 intersecting tSSS components for 1580.000 - 1589.999 s
        Projecting  0 intersecting tSSS components for 1590.000 - 1599.999 s
        Projecting  0 intersecting tSSS components for 1600.000 - 1609.999 s
        Projecting  1 intersecting tSSS component  for 1610.000 - 1619.999 s
        Projecting  0 intersecting tSSS components for 1620.000 - 1629.999 s
        Projecting  0 intersecting tSSS components for 1630.000 - 1639.999 s
        Projecting  0 intersecting tSSS components for 1640.000 - 1649.999 s
        Projecting  0 intersecting tSSS components for 1650.000 - 1659.999 s


/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for 1660.000 - 1669.999 s
        Projecting  0 intersecting tSSS components for 1670.000 - 1679.999 s
        Projecting  0 intersecting tSSS components for 1680.000 - 1689.999 s
        Projecting  0 intersecting tSSS components for 1690.000 - 1699.999 s
        Projecting  0 intersecting tSSS components for 1700.000 - 1709.999 s
        Projecting  0 intersecting tSSS components for 1710.000 - 1719.999 s
        Projecting  0 intersecting tSSS components for 1720.000 - 1729.999 s
        Projecting  0 intersecting tSSS components for 1730.000 - 1739.999 s
        Projecting  0 intersecting tSSS components for 1740.000 - 1749.999 s
        Projecting  1 intersecting tSSS component  for 1750.000 - 1759.999 s


/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for 1760.000 - 1769.999 s
        Projecting  0 intersecting tSSS components for 1770.000 - 1779.999 s
        Projecting  0 intersecting tSSS components for 1780.000 - 1789.999 s
        Projecting  1 intersecting tSSS component  for 1790.000 - 1799.999 s
        Projecting  0 intersecting tSSS components for 1800.000 - 1809.999 s
        Projecting  1 intersecting tSSS component  for 1810.000 - 1819.999 s
        Projecting  0 intersecting tSSS components for 1820.000 - 1829.999 s
        Projecting  0 intersecting tSSS components for 1830.000 - 1839.999 s
        Projecting  0 intersecting tSSS components for 1840.000 - 1849.999 s
        Projecting  0 intersecting tSSS components for 1850.000 - 1859.999 s
        Projecting  1 intersecting tSSS component  for 1860.000 - 1869.999 s
        Projecting  1 intersecting tSSS component  for 1870.000 - 1879.999 s
        Projecting  0 intersecting tSSS components for 1880.000 - 1889.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for 1970.000 - 1979.999 s
        Projecting  0 intersecting tSSS components for 1980.000 - 1989.999 s
        Projecting  1 intersecting tSSS component  for 1990.000 - 1999.999 s
        Projecting  0 intersecting tSSS components for 2000.000 - 2009.999 s
        Projecting  0 intersecting tSSS components for 2010.000 - 2019.999 s
        Projecting  0 intersecting tSSS components for 2020.000 - 2029.999 s
        Projecting  1 intersecting tSSS component  for 2030.000 - 2041.999 s
        Using 84/95 harmonic components for    0.000  (69/80 in, 15/15 out)
[done]
Maxwell filtering completed in 1824.7 seconds
Writing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_1_sss_raw.fif
Closing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_1_sss_raw.fif
Writing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_1_sss_raw-1.fif
Closing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_1_sss_ra

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  1 intersecting tSSS component  for 1710.000 - 1719.999 s
        Projecting  1 intersecting tSSS component  for 1720.000 - 1729.999 s
        Projecting  2 intersecting tSSS components for 1730.000 - 1739.999 s
        Projecting  0 intersecting tSSS components for 1740.000 - 1749.999 s
        Projecting  1 intersecting tSSS component  for 1750.000 - 1759.999 s
        Projecting  4 intersecting tSSS components for 1760.000 - 1769.999 s
        Projecting  2 intersecting tSSS components for 1770.000 - 1788.999 s
        Using 83/95 harmonic components for    0.000  (68/80 in, 15/15 out)
[done]
Maxwell filtering completed in 249.4 seconds
Writing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_2_sss_raw.fif
Closing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_2_sss_raw.fif
Writing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_2_sss_raw-1.fif
Closing /mnt/sphere/nbl/processed_meg/nbl_008/ses-01/nbl_008_bigfrank_2_sss_raw

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  1 intersecting tSSS component  for  570.000 -  579.999 s
        Projecting  0 intersecting tSSS components for  580.000 -  589.999 s
        Projecting  0 intersecting tSSS components for  590.000 -  599.999 s
        Projecting  0 intersecting tSSS components for  600.000 -  609.999 s
        Projecting  0 intersecting tSSS components for  610.000 -  619.999 s
        Projecting  0 intersecting tSSS components for  620.000 -  629.999 s
        Projecting  0 intersecting tSSS components for  630.000 -  639.999 s
        Projecting  0 intersecting tSSS components for  640.000 -  649.999 s
        Projecting  0 intersecting tSSS components for  650.000 -  659.999 s
        Projecting  0 intersecting tSSS components for  660.000 -  669.999 s
        Projecting  0 intersecting tSSS components for  670.000 -  679.999 s
        Projecting  0 intersecting tSSS components for  680.000 -  689.999 s
        Projecting  1 intersecting tSSS component  for  690.000 -  699.999 s

/tmp/ipykernel_2807799/2239389746.py:14: RuntimeWarning: SVD error (SVD did not converge), attempting to use GESVD instead of GESDD
  raw_sss = maxwell_filter(raw, cross_talk=ct_fname, calibration=cal_fname, destination=destination,


        Projecting  0 intersecting tSSS components for 1180.000 - 1189.999 s
        Projecting  1 intersecting tSSS component  for 1190.000 - 1199.999 s
        Projecting  0 intersecting tSSS components for 1200.000 - 1209.999 s
        Projecting  0 intersecting tSSS components for 1210.000 - 1219.999 s
        Projecting  0 intersecting tSSS components for 1220.000 - 1229.999 s
        Projecting  0 intersecting tSSS components for 1230.000 - 1239.999 s
        Projecting  0 intersecting tSSS components for 1240.000 - 1249.999 s
        Projecting  0 intersecting tSSS components for 1250.000 - 1259.999 s
        Projecting  0 intersecting tSSS components for 1260.000 - 1269.999 s
        Projecting  1 intersecting tSSS component  for 1270.000 - 1279.999 s
        Projecting  0 intersecting tSSS components for 1280.000 - 1289.999 s
        Projecting  0 intersecting tSSS components for 1290.000 - 1299.999 s
        Projecting  0 intersecting tSSS components for 1300.000 - 1309.999 s